spring:
  datasource:
    url: jdbc:mysql://localhost:3306/centroxy
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Options: none, update, create, create-drop
    show-sql: true  # Enable SQL query logging

server:
 port: 9090

jwt:
  secretkey: pravat@123

token:
 expiration:
  time: 10
